### ISSUE TITLE
URL to get Provisioning Token

### ISSUE THREAD

**Issue by r0bi** [rgrokett/RaspiAsteriskAlexa#3]
I needed to edit Device ID name in order to get the correct Provisioning Token (as seen below with "YOURDEVICEID". Additionally, had to remove line breaks when copying from PDF.

https://www.amazon.com/ap/oa?client_id=YOURCLIENTID&scope=alexa%3Aall&scope_data=%7B%22alexa%3Aall%22%3A%7B%22productID%22%3A%22YOURDEVICEID%22,%22productInstanceAttributes%22%3A%7B%22deviceSerialNumber%22%3A%2212345%22%7D%7D%7D&response_type=code&redirect_uri=https%3A%2F%2Flocalhost

**Comment by rgrokett** [comment]
Updated PDF doc to reflect correction.  (Amazon tightened security slightly by requiring ProductID to match Application Type ID.)
