### ISSUE TITLE
Can't seem to get 

### ISSUE THREAD

**Issue by jimbolaya** [rgrokett/RaspiAsteriskAlexa#4]
After going through 

> 4. Copy the URL below to a notepad and EDIT to insert your client_id and Paste to your browser.
> https://www.amazon.com/ap/oa?client_id=YOURCLIENTID&scope=alexa%3Aall&scope_data=%7B%22alexa%3Aall%22%3A%7B%22productID%22%3A%22kd_raspi_asterisk%22,%22productInstanceAttributes%22%3A%7B%22deviceSerialNumber%22%3A%2212345%22%7D%7D%7D&response_type=code&redirect_uri=https%3A%2F%2Flocalhost

with my own YOURCLIENTID I never get to the page that has the "https://localhost ..." part in it. It always goes to another screen:

```
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

```

Is this an issue with Amazon? I'm not sure how else to get a provisioning token. I'll do some research on that.

**Comment by rgrokett** [comment]
Updated PDF doc to support security change by Amazon for getting tokens.
