### ISSUE TITLE
Getting RaspiAsteriskAlexa to run on RasPBX/FreePBX

### ISSUE THREAD

**Issue by jimbolaya** [rgrokett/RaspiAsteriskAlexa#5]
I'm sorry this isn't really an issue, more of a howto. 

First off, thank you for doing this. This is one of the coolest projects I've ever done. Also thank you for updating the instructions for getting the tokens.

I got this running on RasPBX. I skipped the sections until I got to "Alexa/Asterisk Install and Configuration" since I already had a running setup on RasPBX.

1) I ran install.sh from /usr/src/RaspiAsteriskAlexa. I probably should have just done it by hand.
2) In the instructions I replaced "/usr/share" with "/var/lib" which is where the asterisk sound directory and the agi-bin directory reside. This includes a path within  .../asterisk/agi-bin/alexa.agi
3) There is no .../sounds/custom directory, so I had to create that with appropriate permissions.
4) For setting up the "AMAZON ALEXA VOICE" extension, the file for the custom extension is different. In FreePBX, the custom extensions live in "/etc/asterisk/extensions_custom.conf". I added the [alexa_tts] to this file and:
```
[ext-local-custom]
include => alexa_tts
```
below the [alexa_tts] section

RasPBX doesn't seem to have a pi user, but that doesn't seem to be needed. I did create one anyway and copied the RaspiAsteriskAlexa directory there just in case. 

If you want to add this to the Wiki or as a Readme that would be fine or I can do it in a commit (though I've never done that before).

**Comment by rgrokett** [comment]
Updated README.md with your comments for using RasPBX instead of basic Asterisk. 
Thanks for info!
