### ISSUE TITLE
WAV format mismatch

### ISSUE THREAD

**Issue by markosjal** [rgrokett/RaspiAsteriskAlexa#6]
[Nov 17 13:04:07] WARNING[9238][C-00000022]: format_wav.c:112 check_header_fmt: Unexpected frequency mismatch 16000 (expecting 8000)
[Nov 17 13:04:07] WARNING[9238][C-00000022]: file.c:398 fn_wrapper: Unable to open format wav
    -- Playing '/tmp/avs_audio9265' (escape_digits=#) (sample_offset 0)

**Comment by rgrokett** [comment]
The Raspian version of Asterisk (11.13) doesn't give this error msg. Is this from FreePBX?

**Comment by markosjal** [comment]
Vanilla asterisk 11.7.0~1ubuntu1 on ubuntu 12.04 x86

It all works so asterisk deals with it some way
