### ISSUE TITLE
Extension flow looping

### ISSUE THREAD

**Issue by scotty-p** [rgrokett/RaspiAsteriskAlexa#9]
This is an awesome project, thanks for making it! 

Just trying to get this going so I'm not sure it's an issue. I've got the PBX all set up and working on a docker container instead of a RasPi. 

When I dial the 5555 extension, the answer plays but doesn't wait to record and loops indefinitely on "Try another question". It doesn't appear that token.pl is being run as there are no /tmp/token* files being generated (this does work running manually). The asterisk logging is pretty average, so I can't tell what's wrong.

Here's my sip.conf:
````
[internal]
exten => 7001,1,Answer()
exten => 7001,2,Dial(SIP/7001,60)
exten => 7001,3,Playback(vm-nobodyavail)
exten => 7001,4,VoiceMail(1000@7001)
exten => 7001,5,Hangup()

exten => 7002,1,Answer()
exten => 7002,2,Dial(SIP/7002,60)
exten => 7002,3,Playback(vm-nobodyavail)
exten => 7002,4,VoiceMail(7002@main)
exten => 7002,5,Hangup()

exten => 8001,1,VoicemailMain(7001@main)
exten => 8001,2,Hangup()

exten => 8002,1,VoicemailMain(7002@main)
exten => 8002,2,Hangup()

include => alexa_tts
include => default

; AMAZON ALEXA VOICE
[alexa_tts]
exten => 5555,1,Answer()
; Get an AWS Token
exten => 5555,n,System(/root/token.pl)
; Play prompts
exten => 5555,n,Playback(./custom/alexa_hello)
exten => 5555,n,Playback(./custom/alexa_example)
; Alexa API integration
exten => 5555,n(record),agi(alexa.agi,en-us)
; Loop
exten => 5555,n,Playback(./custom/alexa_another)
exten => 5555,n,goto(record)
; These are not used currently
exten => 5555,n(goodbye),Playback(vm-goodbye)
exten => 5555,n,Hangup()
````

**Comment by rgrokett** [comment]
If the token.pl works when run on the command line ($ perl /home/pi/token.pl)  then you know the Amazon security is good.  (This is step 10 in the PDF doc.)  

I assume when you say "the answer plays..."   means dialing 5555#, the phone answers and the "After the beep..." audio clips play. This does point to the AGI script not running or exiting on error.

The next thing to check is permissions of the AGI script alexa.agi  & token.pl
`ls -l /usr/share/asterisk/agi-bin/alexa.agi`
Should be something like: 
` -rwxr-xr-x 1 root root  9633 Aug 14 15:25 alexa.agi`
If needed:
`sudo chmod 755 alexa.agi`
Do the same for the /home/pi/token.pl (in your case /root/token.pl) 

Next is to turn on AGI script debugging:
`sudo asterisk -r`
`CLI> agi set debug on`
`CLI> core set debug 4`
This should then display the alexa.agi log messages to the terminal. Make a call and then you can look in the alexa.agi for where in the code the messages get printed. 

You can look at the RaspiAsteriskAlexaInstallation.pdf document (last page) for other hints on troubleshooting if needed.
